MAX_LENGTH_INGREDIENT_NAME = 200
MAX_LENGTH_INGREDIENT_MEASUREMENT_UNIT = 200
MAX_LENGTH_TAG_NAME = 200
MAX_LENGTH_TAG_COLOR = 7
MAX_LENGTH_TAG_SLUG = 200
MAX_LENGTH_RECIPE_NAME = 200

MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1

ADMIN_MIN_NUM_INGREDIENTS = 1
ADMIN_EXTRA_INGREDIENTS = 1
